/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {



    @Test
    public void testPush() {

    }

    @Test
    public void testPop() {

    }

    @Test
    public void testRemoveAllGreater() {

    }
}
