/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import quiz.LinkedList;

import static org.junit.Assert.*;

import java.util.Iterator;

import org.junit.After;
import org.junit.Before;

public class AppTest {

    LinkedList<Integer> list;

    @Before
    public void before() {
        list = new LinkedList<>();
    }

    @After
    public void after() {
       list = new LinkedList<>(); 
    }

    @Test
    public void testPushAndPop() {
        list.push(1);
        list.push(2);
        list.push(3);
        assertEquals(3, list.size());
        list.pop();
        list.pop();
        list.pop();
        assertEquals(0, list.size());

        list.push(3);
        list.push(2);
        list.push(5);
        Iterator<Integer> iter = list.iterator();
        assertEquals(3, iter.next().intValue());
        assertEquals(2, iter.next().intValue());
        assertEquals(5, iter.next().intValue());

        assertEquals(5, list.pop().intValue());
        assertEquals(2, list.pop().intValue());
        assertEquals(3, list.pop().intValue());

        assertEquals(0, list.size());

    }

    @Test
    public void testRemoveAllGreater() {
        assertEquals(0, list.size());
        list.push(1);
        list.push(2);
        list.push(3);
        list.push(6);
        list.push(8);
        list.removeAllGeater(3);
        assertEquals(3, list.pop().intValue());
        assertEquals(2, list.pop().intValue());
        assertEquals(1, list.pop().intValue());
        assertEquals(0, list.size());
    }
}
